-- Question 5:

-- Level: Moderate

-- Topic: JOIN & GROUP BY

-- Task: Create an overview of the actors' first and last names and in how many movies they appear in.

-- Question: Which actor is part of most movies??




-- QUERY:


SELECT 
CONCAT(act.first_name, ' ', act.last_name) AS actor_name,
COUNT(f.film_id) AS n_of_movies
FROM actor AS act
LEFT JOIN film_actor AS fa
ON fa.actor_id = act.actor_id
INNER JOIN film AS f
ON fa.film_id = f.film_id
GROUP BY actor_name
ORDER BY n_of_movies DESC;



-- OUTPUT:


"actor_name"	"n_of_movies"
"SUSAN DAVIS"	54
"GINA DEGENERES"	42
"WALTER TORN"	41
"MARY KEITEL"	40
"MATTHEW CARREY"	39
"SANDRA KILMER"	37
"SCARLETT DAMON"	36
"VAL BOLGER"	35
"HENRY BERRY"	35
"GROUCHO DUNST"	35
"VIVIEN BASINGER"	35
"ANGELA WITHERSPOON"	35
"UMA WOOD"	35
"SIDNEY CROWE"	34
"KIRSTEN AKROYD"	34
"JAYNE NOLTE"	34
"WARREN NOLTE"	34
"ANGELA HUDSON"	34
"SEAN GUINESS"	33
"RENEE TRACY"	33
"BEN WILLIS"	33
"RENEE BALL"	33
"KENNETH TORN"	33
"KEVIN GARLAND"	33
"REESE WEST"	33
"JULIA MCQUEEN"	33
"EWAN GOODING"	33
"ALBERT JOHANSSON"	33
"RIP CRAWFORD"	33
"CAMERON ZELLWEGER"	33
"REESE KILMER"	32
"NATALIE HOPKINS"	32
"HELEN VOIGHT"	32
"CHRISTIAN AKROYD"	32
"WARREN JACKMAN"	32
"GRETA MALDEN"	32
"ED MANSFIELD"	32
"WHOOPI HURT"	32
"HARVEY HOPE"	32
"JULIANNE DENCH"	32
"PENELOPE CRONYN"	31
"WILL WILSON"	31
"RIVER DEAN"	31
"IAN TANDY"	31
"JADA RYDER"	31
"JAMES PITT"	31
"WOODY HOFFMAN"	31
"KARL BERRY"	31
"FAY WINSLET"	31
"ALBERT NOLTE"	31
"DARYL WAHLBERG"	31
"ANGELINA ASTAIRE"	31
"MINNIE ZELLWEGER"	31
"RUSSELL TEMPLE"	31
"MARY TANDY"	31
"WOODY JOLIE"	31
"NICK STALLONE"	30
"MATTHEW LEIGH"	30
"BELA WALKEN"	30
"GREGORY GOODING"	30
"VIVIEN BERGEN"	30
"MICHAEL BOLGER"	30
"CATE MCQUEEN"	30
"ROCK DUKAKIS"	30
"RICHARD PENN"	30
"MENA TEMPLE"	30
"RAY JOHANSSON"	30
"RIP WINSLET"	30
"GRACE MOSTEL"	30
"LUCILLE TRACY"	30
"DARYL CRAWFORD"	30
"JUDE CRUISE"	30
"JOHNNY CAGE"	29
"BURT DUKAKIS"	29
"JOHN SUVARI"	29
"ED GUINESS"	29
"JON CHASE"	29
"JODIE DEGENERES"	29
"ALEC WAYNE"	29
"KENNETH HOFFMAN"	29
"HUMPHREY GARLAND"	29
"JAYNE NEESON"	29
"JOHNNY LOLLOBRIGIDA"	29
"CUBA OLIVIER"	28
"CATE HARRIS"	28
"MAE HOFFMAN"	28
"KIM ALLEN"	28
"RALPH CRUZ"	28
"HARRISON BALE"	28
"DAN HARRIS"	28
"MERYL GIBSON"	28
"MILLA KEITEL"	28
"OLYMPIA PFEIFFER"	28
"GOLDIE BRODY"	28
"TOM MIRANDA"	27
"KIRSTEN PALTROW"	27
"PENELOPE MONROE"	27
"GRETA KEITEL"	27
"MORGAN HOPKINS"	27
"CHRIS BRIDGES"	27
"FRED COSTNER"	27
"JAYNE SILVERSTONE"	27
"AUDREY BAILEY"	27
"DUSTIN TAUTOU"	27
"MEG HAWKE"	27
"GREG CHAPLIN"	27
"GENE MCKELLEN"	27
"MORGAN WILLIAMS"	27
"WILLIAM HACKMAN"	27
"ANNE CRONYN"	27
"ALAN DREYFUSS"	27
"HUMPHREY WILLIS"	26
"FRANCES DAY-LEWIS"	26
"GEOFFREY HESTON"	26
"SCARLETT BENING"	26
"LAURA BRODY"	26
"AL GARLAND"	26
"ELVIS MARX"	26
"LAURENCE BULLOCK"	26
"CARMEN HUNT"	26
"KIRK JOVOVICH"	26
"JIM MOSTEL"	26
"GARY PENN"	26
"GROUCHO SINATRA"	26
"SEAN WILLIAMS"	26
"AUDREY OLIVIER"	25
"MORGAN MCDORMAND"	25
"CUBA ALLEN"	25
"BOB FAWCETT"	25
"JOE SWANK"	25
"CHRISTIAN NEESON"	25
"NICK WAHLBERG"	25
"ZERO CAGE"	25
"LIZA BERGMAN"	25
"ELLEN PRESLEY"	25
"TOM MCKELLEN"	25
"GARY PHOENIX"	25
"RUSSELL BACALL"	25
"GROUCHO WILLIAMS"	25
"JANE JACKMAN"	25
"SALMA NOLTE"	25
"JEFF SILVERSTONE"	25
"PENELOPE PINKETT"	25
"OPRAH KILMER"	25
"LUCILLE DEE"	24
"MENA HOPPER"	24
"DAN STREEP"	24
"CUBA BIRCH"	24
"BURT POSEY"	24
"MICHAEL BENING"	24
"SPENCER DEPP"	24
"MILLA PECK"	24
"CHARLIZE DENCH"	24
"CAMERON STREEP"	24
"DEBBIE AKROYD"	24
"PARKER GOLDBERG"	24
"CARY MCCONAUGHEY"	24
"JULIA BARRYMORE"	24
"FRANCES TOMEI"	23
"BEN HARRIS"	23
"MICHELLE MCCONAUGHEY"	23
"TIM HACKMAN"	23
"JESSICA BAILEY"	23
"GENE WILLIS"	23
"BURT TEMPLE"	23
"LISA MONROE"	23
"JENNIFER DAVIS"	22
"ADAM HOPPER"	22
"MERYL ALLEN"	22
"CHRISTIAN GABLE"	22
"FAY WOOD"	22
"DAN TORN"	22
"ED CHASE"	22
"NICK DEGENERES"	22
"SYLVESTER DERN"	22
"GENE HOPKINS"	22
"KENNETH PALTROW"	21
"SPENCER PECK"	21
"CHRISTOPHER WEST"	21
"KEVIN BLOOM"	21
"KENNETH PESCI"	20
"THORA TEMPLE"	20
"CHRIS DEPP"	20
"CHRISTOPHER BERRY"	20
"BETTE NICHOLSON"	20
"MINNIE KILMER"	20
"RITA REYNOLDS"	20
"MATTHEW JOHANSSON"	20
"FAY KILMER"	20
"SANDRA PECK"	19
"RUSSELL CLOSE"	19
"CAMERON WRAY"	19
"PENELOPE GUINESS"	19
"SISSY SOBIESKI"	18
"ADAM GRANT"	18
"JULIA ZELLWEGER"	16
"JUDY DEAN"	15
"JULIA FAWCETT"	15
"EMILY DEE"	14





-- Answer: Susan Davis with 54 movies

